export const subscriptions = [
  {
    id: "1",
    name: "Netflix",
    icon: "netflix.jpg",
    price: "$14.99",
    planType: "Premium",
    renewalType: "Monthly",
  },
  {
    id: "2",
    name: "Spotify",
    icon: "spotify.png",
    price: "$8.99",
    planType: "Individual",
    renewalType: "Monthly",
  },
  {
    id: "3",
    name: "Disney+",
    icon: "disney+.png",
    price: "$7.99",
    planType: "Standard",
    renewalType: "Monthly",
  },
  {
    id: "4",
    name: "YouTube Premium",
    icon: "youTube.png",
    price: "$11.99",
    planType: "Premium",
    renewalType: "Monthly",
  },
  {
    id: "5",
    name: "Adobe Creative Cloud",
    icon: "adobe-creative-cloud.jpg",
    price: "$52.99",
    planType: "All Apps",
    renewalType: "Monthly",
  },
  {
    id: "6",
    name: "Apple Music",
    icon: "apple-music.png",
    price: "$9.99",
    planType: "Student",
    renewalType: "Monthly",
  },
  {
    id: "7",
    name: "Dropbox",
    icon: "dropbox.png",
    price: "$9.99",
    planType: "Plus",
    renewalType: "Monthly",
  },
  {
    id: "8",
    name: "Figma",
    icon: "figma.png",
    price: "$12.00",
    planType: "Professional",
    renewalType: "Monthly",
  },
  {
    id: "9",
    name: "GitHub Pro",
    icon: "apple-music.png",
    price: "$4.00",
    planType: "Pro",
    renewalType: "Monthly",
  },
];
